# Generated by Django 4.0.2 on 2022-02-24 13:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ageCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.CharField(max_length=64)),
                ('manCount', models.PositiveIntegerField(max_length=10000000)),
                ('womenCount', models.PositiveIntegerField(max_length=10000000)),
            ],
            options={
                'verbose_name_plural': "Aholi Bo'linishi",
            },
        ),
        migrations.CreateModel(
            name='communityEmployes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgUrl', models.ImageField(upload_to='media/comunity')),
                ('fullName', models.CharField(max_length=120)),
                ('address', models.TextField()),
                ('level', models.CharField(max_length=512)),
                ('phoneNumber', models.TextField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Mahala yigini ishchilar',
            },
        ),
        migrations.CreateModel(
            name='employes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgUrl', models.ImageField(upload_to='media/employes')),
                ('fullName', models.CharField(max_length=120)),
                ('address', models.TextField()),
                ('level', models.CharField(max_length=512)),
                ('phoneNumber', models.TextField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Ishchilar',
            },
        ),
        migrations.CreateModel(
            name='nameOfRoads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bossOfRoad', models.CharField(max_length=64)),
                ('nameOfRoad', models.CharField(max_length=128)),
                ('liveAddress', models.CharField(max_length=128)),
                ('phoneNumber', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Kocha Boshlari',
            },
        ),
        migrations.CreateModel(
            name='theDataOfBuildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
