# Generated by Django 4.0.2 on 2022-02-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agecount',
            name='manCount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='agecount',
            name='womenCount',
            field=models.PositiveIntegerField(),
        ),
    ]
