# Generated by Django 4.0.2 on 2022-02-25 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_agecount_mancount_alter_agecount_womencount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ageCount',
        ),
        migrations.DeleteModel(
            name='communityEmployes',
        ),
        migrations.DeleteModel(
            name='employes',
        ),
        migrations.DeleteModel(
            name='nameOfRoads',
        ),
        migrations.DeleteModel(
            name='theDataOfBuildings',
        ),
    ]
