# Generated by Django 4.0.2 on 2022-02-25 12:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Biz haqimizda sahifani tahrirlash',
            },
        ),
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Katagoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=64)),
                ('phoneNumber', models.CharField(max_length=16)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Xabarlar',
            },
        ),
        migrations.AlterModelOptions(
            name='thedataofbuildings',
            options={'verbose_name_plural': 'Asosiy sahifani tahrirlash'},
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', ckeditor.fields.RichTextField()),
                ('select', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.catagory')),
            ],
            options={
                'verbose_name_plural': 'Yangiliklar qoyish',
            },
        ),
    ]
