# Generated by Django 4.0.2 on 2022-02-25 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_about_catagory_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='messageUser',
        ),
    ]
